### ISSUE TITLE
Some metastable isotopes have wrong decay heats

### ISSUE THREAD

**Issue by aruzzo** [pyne/pyne#1145]
After looking more at #1054, there are more metastable isotopes that have a very large decay heat value when used in pyne.material.Material (28 in total that I found): [https://gist.github.com/aruzzo/4dbf3c283eeed8b712e16c150bd19a64](url)
I edited the material.cpp file to print what values the `decay_heat()` function uses. I tested Ag-108m, one of the original problem isotopes from the issue:
```
########OUTPUT FROM material.cpp########
decay constant: 5.77623e+08
q value: 1.636
decay heat: 8.44974e+11
########END FROM material.cpp########
{471080001: 844974163698.3318}
########OUTPUT FROM material.cpp########
decay constant: 5.01473e-11
q value: 0
decay heat: 0
########END FROM material.cpp########
{471080002: 0.0}
```
For id `471080001`, the function retrieves the right q value from the nuc_data.h5 file but the wrong half-life/decay constant. Using id `471080002` gets the right decay constant but a 0 q value (no entry exists in the decay/q_values tree so it defaults to 0). It seems to pull the half-life from the decay/level_list tree, which contains all the different energy levels of the isotopes. For the problematic isotopes, an energy level of 1 exists before the metastable level with an extremely short half-life; the metastable isotopes are the second energy level, which is why using `471080002` retrieves the correct half-life and decay constant.
Also, when parsing through the different ids in the decay/q_values tree, there was one id `162500000` which seems wrong - I don't think an isotope of sulfur exists with a mass of ~250 amu.

**Comment by katyhuff** [comment]
What reference are you using to define "right" ?

**Comment by aruzzo** [comment]
I don't know of another resource to check the q values of the reactions, I assumed they were right. I calculated a few of the decay constants using the half-lives available in the decay/decays tree, which are the same values as in decay/level_list but easier to search through since it has much fewer entries. They were the same values that were used by material.cpp.

**Comment by katyhuff** [comment]
Sorry -- still confused.

You say:
> the function retrieves the right q value 

How do you know?  What is the right q value? Where did you get it from?

> but the wrong half-life/decay constant

I assume you're looking up the decay constant on nndc.bnl.gov and it's different there than is given by the decay_constant function? Please recall that $t_{1/2} = ln(2)/\lambda$

> I don't know of another resource to check the q values of the reactions, I assumed they were right.

What do you mean by "they" in this sentence?

**Comment by aruzzo** [comment]
I did not check with an outside reference if the q values are correct. When I wrote "they", I meant the q values. I only checked that that material.cpp function obtains the corresponding q value for each id from the decay/q_values tree in the nuc_data.h5 file, which it does when using the `zas id`. For the decay constant, I checked with nndc.bnl.gov and converted the half-lives of some of the problematic isotopes to seconds and then calculated the decay constants in order to check that they match. For the problematic isotopes, e.g. Ag-108m, using the id `471080001` returns the incorrect decay constant; material.cpp seems to use the half-life value from the decay/level_list tree, which uses the `state_id` naming convention. So, `471080001` is not the metastable id but rather the first energy state that has an extremely short half-life. The metastable isotope id in the decay/level_list tree is `471080002`, which is why using that value returns the correct decay constant. The half-life of `471080002` and the other isotopes I checked matches with the half-life from nndc.bnl.gov. The decay/q_values tree uses the `zas id` convention which is why `471080002` returns a q value of 0 since only `471080001` exists in that file. This mismatched id problem occurs for the other 27 metastable isotopes.

**Comment by katyhuff** [comment]
Ok -- so I think many of my answers can be parsed from your gist/ notebook. But, it's very difficult to read. 

First, can you please indent and use line length limits according to PEP8 so that github doesn't cut off your code... 

![image](https://user-images.githubusercontent.com/393899/59462137-a4e65b80-8de8-11e9-91f7-abec775025a0.png)

I'm finding the logic of the script is obfuscated somewhat by the concise naming and all-on-one-line coding style. Can you clean it up a little (make your loop clearer, use meaningful names, make the output clear by using human-readable isotope names, and perhaps indicate which output entry is which with more verbose print statements)? 

I'd be happy to look at it again when it's cleaner. I think there may be a fundamental misunderstanding in the issue... particularly with respect to the meaning of the energy levels. The metastable isomers should have quite high decay heats...You may be interested in this benchmark ... ftp://ftp.nrg.eu/pub/www/talys/tendl2014/CCFE-R(15)25.pdf

> q values of the reactions
It's decay we're talking about, so not a reaction exactly, just for the record.

**Comment by katyhuff** [comment]
Ah -- I see you've clarified a bit. Sorry -- I was preparing my comment while you were responding. Will read.

**Comment by nathanb01** [comment]
From what I saw it looked like the confusion lies in what the `0001` flag should mean. In the tutorial on nuclide naming on the website it says that 1 would be the first metastable state, as opposed to the first excited state. However for some isotopes there are isomers listed with lower excitation energy than the first isomer with the metastable flag in the prebuilt nuc data  `decay/level_list`. Therefore one might expect `471080001` (Ag-108) to refer to what is actually `471080002` (wikipedia lists this one as Ag-108m) because it is the first one with the metastable flag (a 1 in the metastable column).

**Comment by nathanb01** [comment]
The decay heat it gives was correctly calculated from the data given the id `471080001` since `471080001` corresponds to the first excited state which had a significantly lower half life but similar magnitude excitation energy as `471080002`.

**Comment by katyhuff** [comment]
yes, I think that's right @nathanb01 . For posterity and confidence, @aruzzo is going to clarify his ipython notebook gist to make clear the observed and expected behavior, and why the expected behavior is expected.

**Comment by aruzzo** [comment]
After looking through `material.cpp` and `data.cpp`, the problem became clear. This new [gist](https://gist.github.com/aruzzo/28cbe1e861436f677d574092c06ad116) hopefully more clearly highlights how `material.Material.decay_heat` doesn't work for some isotopes such as Ag-108m. The issue comes from how `material.Material.decay_heat` calls `data.decay_const`. The `data.decay_const` function uses `state_id` to find the half-life of the isotope from the `nuc_data.h5` file. To do this, `data.decay_const` calls `data.metastable_id` to convert from `zas_id` to `state_id`. However, this functionality only happens in the cython function in `data.pyx`, not the c++ function in `data.cpp`. So, when `material.Material.decay_heat` in `material.cpp` calls `data.decay_const` in `data.cpp`, the decay constant function doesn't call `data.metastable_id`. Thus, it searches for the half-life using the `zas_id`, not the correct `state_id` notation. So, for an isotope such as Ag-108m, `data.decay_const` searches for the half-life using `471080001` instead of its `state_id` `471080002`. This retrieves the half-life of the first energy state, not the metastable state, which happens to be many orders of magnitude shorter than the metastable half-life and thus results in a much greater decay heat.
