### ISSUE TITLE
Openmc python API as optional dependency

### ISSUE THREAD

**Issue by zxkjack123** [pyne/pyne#1166]
PyNE supports reading and writing files of many formats (mcnp, alara, fluka ...). There is a module file for each code (`mcnp.py`, `alara.py`, `fluka.py`, ...). However, things are slightly different for OpenMC.

OpenMC has its own python API (works for python3). It will be very useful if we add `openmc` (OpenMC API) as an optional dependency when we read and write the OpenMC related files, because:
- It's hard and error prone to duplicate OpenMC python API, suggested by @makeclean 
- Users who work with OpenMC and PyNE should have their dependencies on their machine

But there is already a `pyne/openmc.py` in the current PyNE. It contains classes and functions related to OpenMC but are not part of the OpenMC python API. We need to change its name.

I am not sure about the idea of adding `openmc` (OpenMC python API) as an optional dependency is good or not. If we do need it, what's the proper name of current `openmc.py`? `openmc_utils.py`?

What's your opinion? @gonuke @makeclean @pshriwise

**Comment by pshriwise** [comment]
I support that decision, and agree that if one wants to use OpenMC functionality in PyNE, they’ll likely want to have OpenMC installed somewhere on their machine. 

Regarding the `openmc` module in PyNE - I’m wondering, @zxkjack123, if the modules in OpenMC itself might be able to replace what’s in PyNE as well? I know OpenMC has an `ace` module used to parse the ACE data format anyways. Unless perhaps the `pyne/openmc` module has an important purpose for a case where users have PyNE but don’t want to install OpenMC. Maybe more information/background is needed for that decision.

**Comment by zxkjack123** [comment]
@pshriwise In theory, yes, it's possible to use modules in `openmc` to replace the module in `pyne`. But I do not recommend to do that. 

The module `openmc` is an optional module for users who work with OpenMC. For the other users, they do not have `openmc` installed. Replace the  `pyne.ace` with `openmc.ace` will make it a required dependence, it's unfriendly for uses do not use OpenMC.

**Comment by pshriwise** [comment]
Agreed in principle, but I’m wondering how often that case occurs in practice. 

That being said, I’m satisfied with keeping PyNE’s `openmc` module and renaming it.  It does no harm that I can see to keep it in PyNE, even if it isn’t being used. So to answer your initial question about the module name I think your suggestion of `openmc_utils.py` is good.

**Comment by gonuke** [comment]
It's interesting that you point to the `ace` module since I bet @paulromano is probably responsible for both the PyNE version and the OpenMC version.  I am definitely always in favor on convergence, but from my point of view it makes more sense for OpenMC to rely on a robust generally available `ace` module than to require all PyNE users to get OpenMC to read ACE files....  I imagine that @paulromano has the opposite view :smile:

**Comment by paulromano** [comment]
Ha- yes both `pyne.ace` and `openmc.data.ace` are my babies. In an ideal world, I agree that OpenMC would rely on "a robust generally available `ace` module". However, I'm also really dependency-averse which is why I decided against using `pyne.ace` and instead building a homegrown version as part of `openmc.data`. Some things in OpenMC are optional dependencies (e.g., NJOY), but the `openmc.data.ace` module is pretty critical for our data pipeline so there's no way I can make that optional.

Another thing I'll note is that `openmc.data.ace` has gotten more love, bugfixes, refactoring, etc. from myself whereas I have not been actively maintaining `pyne.ace`. At this point, the respective capabilities look a bit different so I'm not sure how feasible it is to try to "converge" the two. The functionality in `openmc.data.ace` is mostly just a thin layer on top of the ACE format that allows us to access the `NXS`, `JXS`, and `XSS` arrays. Actually parsing/interpreting data within those arrays is the responsibility of classes outside of `openmc.data.ace`. For example, we have an `IncidentNeutron.from_ace` method (see examples of use [here](http://docs.openmc.org/en/latest/examples/nuclear-data.html#The-IncidentNeutron-class)).

**Comment by gonuke** [comment]
I understand the sentiment, but dependency-averse projects present a huge challenge for shared solutions like PyNE.  It seems like there has to be a good solution to this.  One way we've tackled it, in part, in some other projects is to simply add an amalgamated PyNE to the project in question.  This is well-demonstrated for pure C++ projects, but maybe less so for Python based projects.  

This seems to be a good community-oriented solution: 
* the owner of the dependent project gets full control over how they engage with the dependency.
* hopefully, if they need improvements in the dependency, they can implement them upstream and pull in a new snapshot

**Comment by paulromano** [comment]
And I understand your sentiment as well. Yeah, I don't know how well amalgamation would work on the Python side. Seems to me that a better solution would be to have pyne be pip-installable (with prebuilt wheels). At that point, I'd be much more open to it being a dependency. I'm not against dependencies for the sake of being against dependencies -- I've just seen how much pain they can cause for both users and developers.

**Comment by gonuke** [comment]
This was resolved in #1167
