### ISSUE TITLE
Transmute for DecayChain Evaluation

### ISSUE THREAD

**Issue by Rolleroo** [pyne/pyne#1223]
Hi There,

I am interested in using the transmute function in Pyne as a simple decay chain evaluator i.e. with the neutron flux set to zero.

First of all I get a QA warning, see below, is this a generic warning or is my build not suitable?
"QAWarning: pyne.endf is not yet QA compliant. 
return f(*args, **kwds)"

Secondly, and more importantly, is this a valid use of this code? Should I get values which approach the true values for long decay chains such as U-238?

Any help, much appreciated.
Kenny

**Comment by gonuke** [comment]
Hello Kenny,

I think the `decay()` method will be better suited to this.  It is more robust for pure decay problems.

Paul

**Comment by Rolleroo** [comment]
Hi @gonuke , thanks for that. Is there any documentation on how this operates? I'd like to use it with a Python application?

**Comment by gonuke** [comment]
Probably not great documentation, but you can look here: http://pyne.io/pyapi/material.html#pyne.material.Material.decay

Basically, 
```
secconds_per_year = 365.25 * 24 * 3600
u_nat = Material({'U238': 0.9929, 'U235': 0.0071})
decay_years = 100
decay_u_nat = u_nat.decay(decay_years * seconds_per_year)
```
will give you a new material object `decay_u_nat` with the composition of the decayed material.

**Comment by Rolleroo** [comment]
Thanks @gonuke , yes that does seem like the kind of output I need, awesome!
If possible, I'd like to output activity of the substances without the sum of the products =1. The activity and normalisation functions don't seem to play well with the output. It may well be my Python naivete coming through, however the syntax doesn't seem obvious from the Materials module functions.
Any assistance gratefully received.
Kenny

**Comment by gonuke** [comment]
A PyNE Material is made up of a composition vector and a total mass.  The composition vector is expressed, by default, in weight percent and thus will always sum to 1.  It is possible to define a different total mass.  

`u_nat.mass = 1000`

When it decays, the mass may change because of mass lost from radiation particles (e.g. alpha), but will be close to the mass you have defined.

The activity method reports the total activity of each species in the material given the specified mass.  It should be a rare coincidence that the activity sums to 1.

**Comment by gonuke** [comment]
Closing since user issue was addressed
