### ISSUE TITLE
Update to Cython 3+

### ISSUE THREAD

**Issue by gonuke** [pyne/pyne#1522]
With API changes in Cython, PyNE no longer functions with version 3.0 of Cython or higher.

This was identified in #1520, and has been seen in other projects.

This issue will be closed when PyNE can by built with newer versions of Cython.

**Comment by ahnaf-tahmid-chowdhury** [comment]
I have recently created a post on Cython users group.
Link: https://groups.google.com/g/cython-users/c/oRziVK9o79E/m/-yWiSIjFAAAJ

**Comment by gonuke** [comment]
@bennibbelink recently tackled this in Cyclus and may have some ideas....

**Comment by bennibbelink** [comment]
I haven't seen this issue before but I think I made appropriate edits to build Pyne with Cython3.  I don't think the problem was with how the object was being dereferenced, but rather which Material class was being referred to (`cpp_material.Material` vs. `pyne.material.Material`).  There were a couple other small changes to be made (convert `cpdef`'ed variables to `cdef`). 

I was able to build `pyne` with Cython3 locally on my [branch](https://github.com/bennibbelink/pyne/tree/cython3), however [CI](https://github.com/bennibbelink/pyne/actions/runs/7952509983) doesn't pass with the cython version unpinned because `moab` doesn't build with Cython3

**Comment by gonuke** [comment]
@pshriwise - do we have any imminent plans for a Cython3+ update to MOAB?

**Comment by ahnaf-tahmid-chowdhury** [comment]
I think MOAB v5.5.1 has Cython3 supports.

**Comment by ahnaf-tahmid-chowdhury** [comment]
I have tested the CI Dockerfile on my local machine with MOAB 5.5.1, and the build was successful. Thanks, @bennibbelink. I think we could proceed with a PR and test on Github CI.

**Comment by bennibbelink** [comment]
Thanks @ahnaf-tahmid-chowdhury, v5.5.1 did the trick
