### ISSUE TITLE
fortran api is missing

### ISSUE THREAD

**Issue by rachelslaybaugh** [pyne/pyne#727]
The C++ and Fortran API only has C++: http://pyne.io/cppapi/index.html. Is that on purpose? I know we wanted to document how to wrap fortran code, we need to sort this out and clarify.

**Comment by nathanb01** [comment]
It looks like this should just be the C++ API because, according to the developer's guide's [entry](https://github.com/pyne/pyne/blob/develop/docs/devsguide/fortran.rst) on fortran, there is not currently a way to interface with PyNE from Fortran. Likely "C++ and Fortran API" should read "C++ API" and the Fortran guide should only appear in the developer's guide.

**Comment by gonuke** [comment]
I agree with @nathanb01 - we should change the title of this link because there is no FORTRAN interface at the moment.  There is fortran code built as part of the transport spatial solvers, but they are wrapped in python and we only publish them through the python interface.

**Comment by gonuke** [comment]
The interface to the transport solvers is documented as part of the Python API

**Comment by gonuke** [comment]
This was closed by #1149, already
