### ISSUE TITLE
nuc_data not found with conda install

### ISSUE THREAD

**Issue by dholladay00** [pyne/pyne#756]
## I have a fresh install of anaconda and have just installed pyne. I run the basic U-235 test and I get the following error: 

> > > print data.atomic_mass('U235')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "data.pyx", line 92, in pyne.data.atomic_mass (/Users/cameronbates/miniconda/conda-bld/work/pyne-0.4-rc1/build/pyne/data.cxx:2712)
> > > ## RuntimeError: File not found: //anaconda/lib/python2.7/site-packages/pyne/nuc_data.h5

Any help on this issue would be greatly appreciated. 

Thanks,
Daniel Holladay

**Comment by katyhuff** [comment]
Hi Daniel,
Were you able to run nuc_data_make successfully? It's buried a little in
the install instructions, but the final step of installation is to create
the nuc_data.h5 file using a script called nuc_data_make. From the linux
install docs: "The setup.py command compiles and installs the PyNE source
code. The nuc_data_make builds and installs a database of nuclear data.
Unfortunately, this must be done as a second step because most nuclear data
is under some form of license restriction or export control which prevents
the developers from distributing it with PyNE. However, the nuc_data_make
program (which is installed by setup.py) will do its best to find relevant
nuclear data elsewhere on your machine or from public sources on the
internet."

That is, from the top-level pyne directory, try the command:

scripts/nuc_data_make

On Wed, Sep 2, 2015 at 6:30 PM, Daniel Holladay notifications@github.com
wrote:

> I have a fresh install of anaconda and have just installed pyne. I run the
> basic U-235 test and I get the following error:
> 
> print data.atomic_mass('U235')
> Traceback (most recent call last):
> File "", line 1, in
> File "data.pyx", line 92, in pyne.data.atomic_mass
> (/Users/cameronbates/miniconda/conda-bld/work/pyne-0.4-rc1/build/pyne/data.cxx:2712)
> RuntimeError: File not found:
> //anaconda/lib/python2.7/site-packages/pyne/nuc_data.h5
> 
> Any help on this issue would be greatly appreciated.
> 
> Thanks,
> Daniel Holladay
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pyne/pyne/issues/756.

## 

http://katyhuff.github.com

**Comment by dholladay00** [comment]
I installed pyne using anaconda on a mac. The instructions on the website are not clear where the nuc_data_make script is when pyne is installed with anaconda. Where is the nuc_data_make script/exec put when pyne is installed with anaconda?

-DH

**Comment by katyhuff** [comment]
Oh. Gotcha. I didn't internalize that, but you did indeed say it already.   It looks to me like that build is pointing at a spot on Cameron's computer, rather than looking for a spot on yours... Cameron ( @crbates ) may have to answer this one.

**Comment by crbates** [comment]
The build is just referring to the source file. nuc_data_make should be in the conda binary directory but it can be run manually using the nuc_data_make.py file under pyne/dbgen in your site-packages directory. I cant gaurantee everything will work as it was built against a much older version of anaconda.

**Comment by katyhuff** [comment]
@skc222 has, in sifting through these issues, pointed out that newer versions of the conda target won't have this issue. So, I think this issue can be safely closed. (any dissent?) Thanks @skc222 !
