### ISSUE TITLE
Ubuntu build script 404 

### ISSUE THREAD

**Issue by clayshieh** [pyne/pyne#796]
The script at:
https://github.com/pyne/install_scripts/blob/master/ubuntu_14.04.sh

does not exist. I tried installing the dependencies manually but hit a wall when installing subversion 1.9.3 but it seems to be a problem with linuxbrew. Any chance the script could be re-uploaded?

**Comment by scopatz** [comment]
I believe that there is now a Ubuntu 15.04 script: https://github.com/pyne/install_scripts/blob/master/ubuntu_15.04.sh  The docs should certainly be updated.  I believe that script will also work on v14.04.  However, after some small digging, here is the 14.04 as too, just in case: https://github.com/pyne/install_scripts/blob/053bc50002323d8335af799e9ee6985fda3b626e/ubuntu_14.04.sh

**Comment by scopatz** [comment]
@elliottbiondo, would you mind please cleaning this stuff up? Thanks!

**Comment by elliottbiondo** [comment]
This was actually fixed a while ago (9c0d7a4ae); the site just needs to be
rebuilt. Unfortunately I am unable to build the site right now due to some
scisphinx issues (converting ipython notebook to html). I don't have time
in the short term to investigate this so if someone else has the ability to
build the site that should clear everything up immediately :)

**Comment by scopatz** [comment]
I was referring to the incorrect link in the readme.

**Comment by elliottbiondo** [comment]
Fixed.

**Comment by scopatz** [comment]
Thanks!

**Comment by gonuke** [comment]
This is resolved by recent updates to the build scripts.
