### ISSUE TITLE
New build system requires sudo

### ISSUE THREAD

**Issue by kkiesling** [pyne/pyne#927]
I believe this issue is a result of PR #906 when the build system was overhauled. To build and install pyne, the `setup.py` command must be run in `sudo`. I think this is coming down to pyne trying build all shared object libraries (ace.so, dagmc.so, etc) into `/pyne/` in the root folder. It is unclear to me how to fix this based on the new system.

I don't think that pyne should require sudo to be built since some people are don't have administrative priveleges on their computer.

**Comment by ljacobson64** [comment]
I'm getting the same error. Definitely looks like a bug.

```
CMake Error at pyne/cmake_install.cmake:50 (file):
  file cannot create directory: /pyne.  Maybe need administrative privileges.
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)


Makefile:107: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by ljacobson64** [comment]
I think I found the problem. In the initial cmake setup, these lines appear:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: getsitepackages() takes no arguments (1 given)
-- PYTHON_EXECUTABLE: /usr/bin/python
-- PYTHON_SITE_PACKAGES:
```

This error leave the `PYTHON_SITE_PACKAGES` variable unset. Then line 39 of `pyne/CMakeLists.txt` says

```
install(TARGETS ${cymod} LIBRARY DESTINATION "${PYTHON_SITE_PACKAGES}/pyne")
```

which then tries to install things to `/pyne`.

**Comment by scopatz** [comment]
Thanks for reporting @kkiesling @ljacobson64. I assume that you are using the system Python and then for some reason it is picking up the system site-packages rather than the user one.  Are you running setup.py with `--user`?  Can you please post the full output of a clean build in a gist or somesuch? Thanks!

**Comment by ljacobson64** [comment]
@scopatz The same problem occurs on CI. If you go [here](https://circleci.com/gh/pyne/pyne/180), click "Building PyNE", and scroll down a bit, you'll see the same error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: getsitepackages() takes no arguments (1 given)
-- PYTHON_EXECUTABLE: /usr/bin/python
-- PYTHON_SITE_PACKAGES: 
```

which leaves `PYTHON_SITE_PACKAGES` unset. If you scroll down further, you'll see a number of lines like

```
-- Installing: /pyne/ace.so
```

indicating that it is installing things to `/pyne`. The only reason the CI passes is because it has sudo permissions.

**Comment by kkiesling** [comment]
Thanks @ljacobson64 and @scopatz for addressing this! (and apologies for my lack of participation in the conversation to get it fixed).
