### ISSUE TITLE
Documentation not quite correct re python version

### ISSUE THREAD

**Issue by makeclean** [pyne/pyne#989]
We actually need python 2.7.8 as the minimum version, I happen to have access to a particularly decrepid 2.7.5 distro which fails to get cram stuff.

**Comment by scopatz** [comment]
Weird.  What was the error?

**Comment by ZoeRichter** [comment]
I'd like to fix the documentation, but since this is a couple years old - is 2.7.8 still the minimum version, and is python 2 going to be supported going forward?

(and if python2 is still being supported and 2.7.8 is not the minimum version necessary, what is the best way to find the new minimum version?)

**Comment by gonuke** [comment]
Someone should probably test on an older python, but I'm all for changing the documentation to say that Py2 is deprecated and that v3.x is required.  Not sure what minor version of py3 is appropriate, though?

**Comment by ZoeRichter** [comment]
Based on a docker I ran, python 3.5.2+ should be the minimum required python, provided we drop support for python 2.  @nsryan2 is working on the dependencies portion of the webpage, is the readme the only thing in the repo that needs editing to reflex this requirement?

**Comment by gonuke** [comment]
closed by #1288
